export const YEARS = Array.from({ length: 37 }, (_, i) => String(2026 - i));

/** USA marketplace body styles (Cars.com / Autotrader). */
export const BODY_TYPES = [
  "Sedan",
  "SUV",
  "Coupe",
  "Truck",
  "Hatchback",
  "Convertible",
  "Van",
  "Wagon",
] as const;

export type BodyType = (typeof BODY_TYPES)[number];

type CatalogModel = { name: string; bodyType: BodyType };

/** Current and recent USA-market models with official body style. */
export const VEHICLES: Record<string, CatalogModel[]> = {
  Acura: [
    { name: "Integra", bodyType: "Hatchback" },
    { name: "TLX", bodyType: "Sedan" },
    { name: "ADX", bodyType: "SUV" },
    { name: "RDX", bodyType: "SUV" },
    { name: "MDX", bodyType: "SUV" },
    { name: "ZDX", bodyType: "SUV" },
  ],
  "Alfa Romeo": [
    { name: "Giulia", bodyType: "Sedan" },
    { name: "Stelvio", bodyType: "SUV" },
    { name: "Tonale", bodyType: "SUV" },
  ],
  Audi: [
    { name: "A3", bodyType: "Sedan" },
    { name: "A4", bodyType: "Sedan" },
    { name: "A5", bodyType: "Coupe" },
    { name: "A6", bodyType: "Sedan" },
    { name: "A7", bodyType: "Hatchback" },
    { name: "A8", bodyType: "Sedan" },
    { name: "Q3", bodyType: "SUV" },
    { name: "Q4 e-tron", bodyType: "SUV" },
    { name: "Q5", bodyType: "SUV" },
    { name: "Q7", bodyType: "SUV" },
    { name: "Q8", bodyType: "SUV" },
    { name: "e-tron GT", bodyType: "Sedan" },
  ],
  BMW: [
    { name: "2 Series", bodyType: "Coupe" },
    { name: "3 Series", bodyType: "Sedan" },
    { name: "4 Series", bodyType: "Coupe" },
    { name: "5 Series", bodyType: "Sedan" },
    { name: "7 Series", bodyType: "Sedan" },
    { name: "8 Series", bodyType: "Coupe" },
    { name: "X1", bodyType: "SUV" },
    { name: "X3", bodyType: "SUV" },
    { name: "X5", bodyType: "SUV" },
    { name: "X7", bodyType: "SUV" },
    { name: "Z4", bodyType: "Convertible" },
    { name: "i4", bodyType: "Hatchback" },
    { name: "iX", bodyType: "SUV" },
    { name: "M3", bodyType: "Sedan" },
    { name: "M4", bodyType: "Coupe" },
    { name: "M5", bodyType: "Sedan" },
  ],
  Buick: [
    { name: "Encore GX", bodyType: "SUV" },
    { name: "Envista", bodyType: "SUV" },
    { name: "Envision", bodyType: "SUV" },
    { name: "Enclave", bodyType: "SUV" },
  ],
  Cadillac: [
    { name: "CT4", bodyType: "Sedan" },
    { name: "CT5", bodyType: "Sedan" },
    { name: "XT4", bodyType: "SUV" },
    { name: "XT5", bodyType: "SUV" },
    { name: "XT6", bodyType: "SUV" },
    { name: "Escalade", bodyType: "SUV" },
    { name: "Lyriq", bodyType: "SUV" },
    { name: "Optiq", bodyType: "SUV" },
  ],
  Chevrolet: [
    { name: "Malibu", bodyType: "Sedan" },
    { name: "Camaro", bodyType: "Coupe" },
    { name: "Corvette", bodyType: "Coupe" },
    { name: "Trax", bodyType: "SUV" },
    { name: "Trailblazer", bodyType: "SUV" },
    { name: "Equinox", bodyType: "SUV" },
    { name: "Blazer", bodyType: "SUV" },
    { name: "Traverse", bodyType: "SUV" },
    { name: "Tahoe", bodyType: "SUV" },
    { name: "Suburban", bodyType: "SUV" },
    { name: "Colorado", bodyType: "Truck" },
    { name: "Silverado 1500", bodyType: "Truck" },
    { name: "Silverado 2500HD", bodyType: "Truck" },
    { name: "Bolt EV", bodyType: "Hatchback" },
  ],
  Chrysler: [
    { name: "300", bodyType: "Sedan" },
    { name: "Pacifica", bodyType: "Van" },
  ],
  Dodge: [
    { name: "Hornet", bodyType: "SUV" },
    { name: "Durango", bodyType: "SUV" },
    { name: "Charger", bodyType: "Sedan" },
    { name: "Challenger", bodyType: "Coupe" },
  ],
  Ford: [
    { name: "Mustang", bodyType: "Coupe" },
    { name: "Mustang Convertible", bodyType: "Convertible" },
    { name: "Escape", bodyType: "SUV" },
    { name: "Bronco Sport", bodyType: "SUV" },
    { name: "Bronco", bodyType: "SUV" },
    { name: "Explorer", bodyType: "SUV" },
    { name: "Edge", bodyType: "SUV" },
    { name: "Expedition", bodyType: "SUV" },
    { name: "Mustang Mach-E", bodyType: "SUV" },
    { name: "Maverick", bodyType: "Truck" },
    { name: "Ranger", bodyType: "Truck" },
    { name: "F-150", bodyType: "Truck" },
    { name: "F-250 Super Duty", bodyType: "Truck" },
    { name: "Transit", bodyType: "Van" },
  ],
  Genesis: [
    { name: "G70", bodyType: "Sedan" },
    { name: "G80", bodyType: "Sedan" },
    { name: "G90", bodyType: "Sedan" },
    { name: "GV60", bodyType: "SUV" },
    { name: "GV70", bodyType: "SUV" },
    { name: "GV80", bodyType: "SUV" },
  ],
  GMC: [
    { name: "Terrain", bodyType: "SUV" },
    { name: "Acadia", bodyType: "SUV" },
    { name: "Yukon", bodyType: "SUV" },
    { name: "Yukon XL", bodyType: "SUV" },
    { name: "Canyon", bodyType: "Truck" },
    { name: "Sierra 1500", bodyType: "Truck" },
    { name: "Sierra 2500HD", bodyType: "Truck" },
    { name: "Hummer EV Pickup", bodyType: "Truck" },
    { name: "Hummer EV SUV", bodyType: "SUV" },
  ],
  Honda: [
    { name: "Civic", bodyType: "Sedan" },
    { name: "Civic Hatchback", bodyType: "Hatchback" },
    { name: "Accord", bodyType: "Sedan" },
    { name: "HR-V", bodyType: "SUV" },
    { name: "CR-V", bodyType: "SUV" },
    { name: "Passport", bodyType: "SUV" },
    { name: "Pilot", bodyType: "SUV" },
    { name: "Prologue", bodyType: "SUV" },
    { name: "Ridgeline", bodyType: "Truck" },
    { name: "Odyssey", bodyType: "Van" },
  ],
  Hyundai: [
    { name: "Elantra", bodyType: "Sedan" },
    { name: "Sonata", bodyType: "Sedan" },
    { name: "Ioniq 6", bodyType: "Sedan" },
    { name: "Venue", bodyType: "SUV" },
    { name: "Kona", bodyType: "SUV" },
    { name: "Tucson", bodyType: "SUV" },
    { name: "Santa Fe", bodyType: "SUV" },
    { name: "Palisade", bodyType: "SUV" },
    { name: "Ioniq 5", bodyType: "SUV" },
    { name: "Santa Cruz", bodyType: "Truck" },
  ],
  Infiniti: [
    { name: "Q50", bodyType: "Sedan" },
    { name: "QX50", bodyType: "SUV" },
    { name: "QX55", bodyType: "SUV" },
    { name: "QX60", bodyType: "SUV" },
    { name: "QX80", bodyType: "SUV" },
  ],
  Jaguar: [
    { name: "XF", bodyType: "Sedan" },
    { name: "F-PACE", bodyType: "SUV" },
    { name: "E-PACE", bodyType: "SUV" },
    { name: "I-PACE", bodyType: "SUV" },
    { name: "F-TYPE", bodyType: "Coupe" },
    { name: "F-TYPE Convertible", bodyType: "Convertible" },
  ],
  Jeep: [
    { name: "Compass", bodyType: "SUV" },
    { name: "Cherokee", bodyType: "SUV" },
    { name: "Grand Cherokee", bodyType: "SUV" },
    { name: "Wrangler", bodyType: "SUV" },
    { name: "Wagoneer", bodyType: "SUV" },
    { name: "Grand Wagoneer", bodyType: "SUV" },
    { name: "Gladiator", bodyType: "Truck" },
  ],
  Kia: [
    { name: "Forte", bodyType: "Sedan" },
    { name: "K4", bodyType: "Sedan" },
    { name: "K5", bodyType: "Sedan" },
    { name: "Soul", bodyType: "Hatchback" },
    { name: "Seltos", bodyType: "SUV" },
    { name: "Sportage", bodyType: "SUV" },
    { name: "Sorento", bodyType: "SUV" },
    { name: "Telluride", bodyType: "SUV" },
    { name: "Niro", bodyType: "SUV" },
    { name: "EV6", bodyType: "SUV" },
    { name: "EV9", bodyType: "SUV" },
    { name: "Carnival", bodyType: "Van" },
  ],
  "Land Rover": [
    { name: "Defender", bodyType: "SUV" },
    { name: "Discovery", bodyType: "SUV" },
    { name: "Discovery Sport", bodyType: "SUV" },
    { name: "Range Rover Evoque", bodyType: "SUV" },
    { name: "Range Rover Velar", bodyType: "SUV" },
    { name: "Range Rover Sport", bodyType: "SUV" },
    { name: "Range Rover", bodyType: "SUV" },
  ],
  Lexus: [
    { name: "IS", bodyType: "Sedan" },
    { name: "ES", bodyType: "Sedan" },
    { name: "LS", bodyType: "Sedan" },
    { name: "RC", bodyType: "Coupe" },
    { name: "LC", bodyType: "Coupe" },
    { name: "UX", bodyType: "SUV" },
    { name: "NX", bodyType: "SUV" },
    { name: "RX", bodyType: "SUV" },
    { name: "TX", bodyType: "SUV" },
    { name: "GX", bodyType: "SUV" },
    { name: "LX", bodyType: "SUV" },
    { name: "RZ", bodyType: "SUV" },
  ],
  Lincoln: [
    { name: "Corsair", bodyType: "SUV" },
    { name: "Nautilus", bodyType: "SUV" },
    { name: "Aviator", bodyType: "SUV" },
    { name: "Navigator", bodyType: "SUV" },
  ],
  Lucid: [
    { name: "Air", bodyType: "Sedan" },
    { name: "Gravity", bodyType: "SUV" },
  ],
  Mazda: [
    { name: "Mazda3", bodyType: "Sedan" },
    { name: "Mazda3 Hatchback", bodyType: "Hatchback" },
    { name: "CX-30", bodyType: "SUV" },
    { name: "CX-5", bodyType: "SUV" },
    { name: "CX-50", bodyType: "SUV" },
    { name: "CX-70", bodyType: "SUV" },
    { name: "CX-90", bodyType: "SUV" },
    { name: "MX-5 Miata", bodyType: "Convertible" },
  ],
  "Mercedes-Benz": [
    { name: "A-Class", bodyType: "Sedan" },
    { name: "C-Class", bodyType: "Sedan" },
    { name: "E-Class", bodyType: "Sedan" },
    { name: "S-Class", bodyType: "Sedan" },
    { name: "CLA", bodyType: "Sedan" },
    { name: "CLE", bodyType: "Coupe" },
    { name: "GLA", bodyType: "SUV" },
    { name: "GLB", bodyType: "SUV" },
    { name: "GLC", bodyType: "SUV" },
    { name: "GLE", bodyType: "SUV" },
    { name: "GLS", bodyType: "SUV" },
    { name: "G-Class", bodyType: "SUV" },
    { name: "EQE", bodyType: "Sedan" },
    { name: "EQS", bodyType: "Sedan" },
    { name: "SL", bodyType: "Convertible" },
    { name: "Sprinter", bodyType: "Van" },
  ],
  Mini: [
    { name: "Cooper", bodyType: "Hatchback" },
    { name: "Cooper Convertible", bodyType: "Convertible" },
    { name: "Countryman", bodyType: "SUV" },
  ],
  Mitsubishi: [
    { name: "Mirage", bodyType: "Hatchback" },
    { name: "Outlander Sport", bodyType: "SUV" },
    { name: "Eclipse Cross", bodyType: "SUV" },
    { name: "Outlander", bodyType: "SUV" },
  ],
  Nissan: [
    { name: "Versa", bodyType: "Sedan" },
    { name: "Sentra", bodyType: "Sedan" },
    { name: "Altima", bodyType: "Sedan" },
    { name: "Maxima", bodyType: "Sedan" },
    { name: "Leaf", bodyType: "Hatchback" },
    { name: "Kicks", bodyType: "SUV" },
    { name: "Rogue", bodyType: "SUV" },
    { name: "Murano", bodyType: "SUV" },
    { name: "Pathfinder", bodyType: "SUV" },
    { name: "Armada", bodyType: "SUV" },
    { name: "Ariya", bodyType: "SUV" },
    { name: "Frontier", bodyType: "Truck" },
    { name: "Titan", bodyType: "Truck" },
    { name: "Z", bodyType: "Coupe" },
  ],
  Polestar: [
    { name: "2", bodyType: "Hatchback" },
    { name: "3", bodyType: "SUV" },
    { name: "4", bodyType: "SUV" },
  ],
  Porsche: [
    { name: "718 Cayman", bodyType: "Coupe" },
    { name: "718 Boxster", bodyType: "Convertible" },
    { name: "911", bodyType: "Coupe" },
    { name: "911 Convertible", bodyType: "Convertible" },
    { name: "Panamera", bodyType: "Sedan" },
    { name: "Macan", bodyType: "SUV" },
    { name: "Cayenne", bodyType: "SUV" },
    { name: "Taycan", bodyType: "Sedan" },
    { name: "Taycan Cross Turismo", bodyType: "Wagon" },
  ],
  Ram: [
    { name: "1500", bodyType: "Truck" },
    { name: "2500", bodyType: "Truck" },
    { name: "3500", bodyType: "Truck" },
    { name: "ProMaster", bodyType: "Van" },
  ],
  Rivian: [
    { name: "R1T", bodyType: "Truck" },
    { name: "R1S", bodyType: "SUV" },
    { name: "R2", bodyType: "SUV" },
  ],
  Subaru: [
    { name: "Impreza", bodyType: "Hatchback" },
    { name: "Legacy", bodyType: "Sedan" },
    { name: "WRX", bodyType: "Sedan" },
    { name: "BRZ", bodyType: "Coupe" },
    { name: "Crosstrek", bodyType: "SUV" },
    { name: "Forester", bodyType: "SUV" },
    { name: "Outback", bodyType: "Wagon" },
    { name: "Ascent", bodyType: "SUV" },
    { name: "Solterra", bodyType: "SUV" },
  ],
  Tesla: [
    { name: "Model 3", bodyType: "Sedan" },
    { name: "Model Y", bodyType: "SUV" },
    { name: "Model S", bodyType: "Sedan" },
    { name: "Model X", bodyType: "SUV" },
    { name: "Cybertruck", bodyType: "Truck" },
  ],
  Toyota: [
    { name: "Corolla", bodyType: "Sedan" },
    { name: "Corolla Hatchback", bodyType: "Hatchback" },
    { name: "Camry", bodyType: "Sedan" },
    { name: "Camry Hybrid", bodyType: "Sedan" },
    { name: "Crown", bodyType: "Sedan" },
    { name: "Prius", bodyType: "Hatchback" },
    { name: "GR86", bodyType: "Coupe" },
    { name: "GR Corolla", bodyType: "Hatchback" },
    { name: "Supra", bodyType: "Coupe" },
    { name: "Corolla Cross", bodyType: "SUV" },
    { name: "RAV4", bodyType: "SUV" },
    { name: "Venza", bodyType: "SUV" },
    { name: "Highlander", bodyType: "SUV" },
    { name: "Grand Highlander", bodyType: "SUV" },
    { name: "4Runner", bodyType: "SUV" },
    { name: "Sequoia", bodyType: "SUV" },
    { name: "Land Cruiser", bodyType: "SUV" },
    { name: "bZ4X", bodyType: "SUV" },
    { name: "Tacoma", bodyType: "Truck" },
    { name: "Tundra", bodyType: "Truck" },
    { name: "Sienna", bodyType: "Van" },
  ],
  Volkswagen: [
    { name: "Jetta", bodyType: "Sedan" },
    { name: "Golf GTI", bodyType: "Hatchback" },
    { name: "Golf R", bodyType: "Hatchback" },
    { name: "Taos", bodyType: "SUV" },
    { name: "Tiguan", bodyType: "SUV" },
    { name: "Atlas", bodyType: "SUV" },
    { name: "ID.4", bodyType: "SUV" },
    { name: "ID. Buzz", bodyType: "Van" },
  ],
  Volvo: [
    { name: "S60", bodyType: "Sedan" },
    { name: "S90", bodyType: "Sedan" },
    { name: "V60", bodyType: "Wagon" },
    { name: "V90", bodyType: "Wagon" },
    { name: "EX30", bodyType: "SUV" },
    { name: "XC40", bodyType: "SUV" },
    { name: "XC60", bodyType: "SUV" },
    { name: "XC90", bodyType: "SUV" },
    { name: "EX90", bodyType: "SUV" },
  ],
};

export const MAKES = Object.keys(VEHICLES);

export const MODELS: Record<string, string[]> = Object.fromEntries(
  Object.entries(VEHICLES).map(([make, models]) => [make, models.map((m) => m.name)]),
);

export function modelsFor(make: string): string[] {
  if (make && MODELS[make]) return MODELS[make];
  return [...new Set(Object.values(MODELS).flat())].sort((a, b) => a.localeCompare(b));
}

export function makeForModel(model: string): string | undefined {
  return MAKES.find((make) => MODELS[make]?.includes(model));
}

export function bodyTypeFor(make: string, model: string): BodyType | undefined {
  if (make && model) {
    const match = VEHICLES[make]?.find((m) => m.name === model);
    if (match) return match.bodyType;
  }
  for (const models of Object.values(VEHICLES)) {
    const match = models.find((m) => m.name === model);
    if (match) return match.bodyType;
  }
  return undefined;
}

/** Body styles sold for this make, or the one style for a specific model. */
export function bodyTypesFor(make: string, model?: string): BodyType[] {
  if (model) {
    const exact = bodyTypeFor(make, model);
    if (exact) return [exact];
  }
  const source = make && VEHICLES[make] ? VEHICLES[make] : Object.values(VEHICLES).flat();
  return [...new Set(source.map((m) => m.bodyType))];
}

export const TRANSMISSIONS = ["Automatic", "Manual", "CVT", "DCT"];
export const FUEL_TYPES = ["Gasoline", "Diesel", "Hybrid", "Plug-in Hybrid", "Electric"];
export const DRIVETRAINS = ["FWD", "RWD", "AWD", "4WD"];
export const COLORS = [
  "Black",
  "White",
  "Silver",
  "Gray",
  "Red",
  "Blue",
  "Green",
  "Brown",
  "Beige",
  "Orange",
];

export const FEATURES = [
  "Sunroof",
  "Leather Seats",
  "Backup Camera",
  "Navigation",
  "Heated Seats",
  "Apple CarPlay",
  "Android Auto",
  "Blind Spot Monitor",
  "Lane Keep Assist",
  "Adaptive Cruise",
  "Premium Audio",
  "Third Row",
  "Tow Package",
  "Panoramic Roof",
  "Ventilated Seats",
  "Wireless Charging",
];

export const STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const CITIES: Record<string, string[]> = {
  Alabama: ["Birmingham", "Huntsville", "Montgomery", "Mobile"],
  Alaska: ["Anchorage", "Fairbanks", "Juneau"],
  Arizona: ["Phoenix", "Scottsdale", "Tucson", "Mesa", "Chandler"],
  Arkansas: ["Little Rock", "Fayetteville", "Fort Smith"],
  California: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento", "Irvine", "Oakland"],
  Colorado: ["Denver", "Boulder", "Colorado Springs", "Aurora"],
  Connecticut: ["Hartford", "New Haven", "Stamford"],
  Delaware: ["Wilmington", "Dover", "Newark"],
  Florida: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "Naples"],
  Georgia: ["Atlanta", "Savannah", "Augusta", "Marietta"],
  Hawaii: ["Honolulu", "Hilo", "Kailua"],
  Idaho: ["Boise", "Meridian", "Idaho Falls"],
  Illinois: ["Chicago", "Aurora", "Naperville", "Joliet", "Evanston"],
  Indiana: ["Indianapolis", "Fort Wayne", "Bloomington"],
  Iowa: ["Des Moines", "Cedar Rapids", "Iowa City"],
  Kansas: ["Wichita", "Overland Park", "Kansas City"],
  Kentucky: ["Louisville", "Lexington", "Bowling Green"],
  Louisiana: ["New Orleans", "Baton Rouge", "Shreveport"],
  Maine: ["Portland", "Augusta", "Bangor"],
  Maryland: ["Baltimore", "Annapolis", "Bethesda"],
  Massachusetts: ["Boston", "Cambridge", "Worcester"],
  Michigan: ["Detroit", "Ann Arbor", "Grand Rapids"],
  Minnesota: ["Minneapolis", "Saint Paul", "Rochester"],
  Mississippi: ["Jackson", "Gulfport", "Biloxi"],
  Missouri: ["Kansas City", "St. Louis", "Springfield"],
  Montana: ["Billings", "Missoula", "Bozeman"],
  Nebraska: ["Omaha", "Lincoln"],
  Nevada: ["Las Vegas", "Reno", "Henderson"],
  "New Hampshire": ["Manchester", "Nashua", "Concord"],
  "New Jersey": ["Newark", "Jersey City", "Princeton"],
  "New Mexico": ["Albuquerque", "Santa Fe", "Las Cruces"],
  "New York": ["New York", "Buffalo", "Rochester", "Albany", "Syracuse"],
  "North Carolina": ["Charlotte", "Raleigh", "Durham", "Asheville"],
  "North Dakota": ["Fargo", "Bismarck"],
  Ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo"],
  Oklahoma: ["Oklahoma City", "Tulsa"],
  Oregon: ["Portland", "Eugene", "Salem"],
  Pennsylvania: ["Philadelphia", "Pittsburgh", "Harrisburg"],
  "Rhode Island": ["Providence", "Newport"],
  "South Carolina": ["Charleston", "Columbia", "Greenville"],
  "South Dakota": ["Sioux Falls", "Rapid City"],
  Tennessee: ["Nashville", "Memphis", "Knoxville"],
  Texas: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "Plano"],
  Utah: ["Salt Lake City", "Provo", "Park City"],
  Vermont: ["Burlington", "Montpelier"],
  Virginia: ["Richmond", "Virginia Beach", "Arlington", "Norfolk"],
  Washington: ["Seattle", "Tacoma", "Bellevue", "Spokane"],
  "West Virginia": ["Charleston", "Morgantown"],
  Wisconsin: ["Milwaukee", "Madison", "Green Bay"],
  Wyoming: ["Cheyenne", "Jackson"],
};

export function citiesFor(state: string): string[] {
  if (state && CITIES[state]) return CITIES[state];
  return [...new Set(Object.values(CITIES).flat())].sort((a, b) => a.localeCompare(b));
}

export function decodeVin(vin: string) {
  const clean = vin.trim().toUpperCase();
  if (clean.length !== 17 || !/^[A-HJ-NPR-Z0-9]{17}$/.test(clean)) return null;
  const map = [
    { make: "Honda", model: "Civic", year: "2022", trim: "EX", bodyType: "Sedan" },
    { make: "Toyota", model: "Camry", year: "2020", trim: "XLE", bodyType: "Sedan" },
    { make: "BMW", model: "M4", year: "2023", trim: "Competition", bodyType: "Coupe" },
    { make: "Ford", model: "F-150", year: "2021", trim: "Lariat", bodyType: "Truck" },
    { make: "Tesla", model: "Model 3", year: "2024", trim: "Long Range", bodyType: "Sedan" },
  ];
  const idx = clean.split("").reduce((n, c) => n + c.charCodeAt(0), 0) % map.length;
  return map[idx];
}
