import { IMAGES } from "./images";
import type { Addon, AppNotification, Conversation, Listing, Plan, User } from "./types";
import { emptyDraft } from "./types";

export const seedUsers: User[] = [
  {
    id: "u1",
    fullName: "Alex Rivera",
    email: "alex@sellmyauto.com",
    phone: "5552018844",
    password: "DriveDirect1",
    role: "user",
    verified: true,
    subscriptionId: "plan-featured",
    addonIds: [],
  },
  {
    id: "u-maya",
    fullName: "Maya Chen",
    email: "maya@sellmyauto.com",
    phone: "5125550188",
    password: "DriveDirect1",
    role: "user",
    verified: true,
    addonIds: [],
  },
  {
    id: "u-derek",
    fullName: "Derek Holt",
    email: "derek@sellmyauto.com",
    phone: "7205550144",
    password: "DriveDirect1",
    role: "user",
    verified: true,
    addonIds: [],
  },
  {
    id: "u-sofia",
    fullName: "Sofia Alvarez",
    email: "sofia@sellmyauto.com",
    phone: "3055550190",
    password: "DriveDirect1",
    role: "user",
    verified: true,
    addonIds: [],
  },
  {
    id: "u-marcus",
    fullName: "Marcus Webb",
    email: "marcus@sellmyauto.com",
    phone: "6025550172",
    password: "DriveDirect1",
    role: "user",
    verified: true,
    addonIds: [],
  },
  {
    id: "u-admin",
    fullName: "Admin User",
    email: "admin@sellmyautousa.com",
    phone: "5550000000",
    password: "AdminDemo1",
    role: "admin",
    verified: true,
    addonIds: [],
  },
];

export function sellerFor(ownerId: string): User | undefined {
  return seedUsers.find((u) => u.id === ownerId);
}

export const seedPlans: Plan[] = [
  {
    id: "plan-basic",
    kind: "basic",
    name: "Basic",
    price: 29,
    durationDays: 30,
    photoLimit: 15,
    featured: false,
    includes: ["15 photos", "Standard placement", "In-app inbox", "30-day listing"],
  },
  {
    id: "plan-featured",
    kind: "featured",
    name: "Featured",
    price: 79,
    durationDays: 30,
    photoLimit: 40,
    featured: true,
    includes: ["40 photos", "Featured placement", "Homepage boost", "30-day listing"],
  },
  {
    id: "plan-bundle",
    kind: "bundle",
    name: "Bundle",
    price: 129,
    durationDays: 60,
    photoLimit: 60,
    featured: true,
    includes: ["60 photos", "Featured + addon boosts", "Video slot", "60-day listing"],
  },
];

export const seedAddons: Addon[] = [
  {
    id: "addon-boost",
    name: "Add Featured Boost",
    price: 25,
    description: "Pin your listing higher in Search for 7 days.",
  },
];

function listing(
  partial: Partial<Listing> & Pick<Listing, "id" | "ownerId" | "year" | "make" | "model" | "price" | "thumbnail" | "status">,
): Listing {
  return {
    ...emptyDraft(),
    trim: "",
    bodyType: "Sedan",
    vin: "",
    vinDecoded: false,
    mileage: "42000",
    transmission: "Automatic",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    engineSize: "2.0L",
    exteriorColor: "Black",
    interiorColor: "Black",
    seats: "5",
    doors: "4",
    state: "California",
    city: "Los Angeles",
    features: ["Backup Camera", "Apple CarPlay"],
    priceStance: "negotiable",
    gallery: [],
    video: "",
    historyReport: "",
    commMode: "chat_phone",
    featured: false,
    createdAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    updatedAt: new Date().toISOString(),
    views: 0,
    favorites: 0,
    chats: 0,
    subscriptionId: "plan-featured",
    addonId: "",
    bundleId: "",
    titleStatus: "Clean",
    owners: "1",
    accidents: "0",
    zip: "90012",
    listedLabel: "Listed 2 days ago",
    ...partial,
  };
}

export const seedListings: Listing[] = [
  listing({
    id: "l1",
    ownerId: "u1",
    year: "2023",
    make: "BMW",
    model: "M4",
    trim: "Competition",
    bodyType: "Coupe",
    price: "72900",
    priceStance: "firm",
    thumbnail: IMAGES.bmwGallery[0],
    gallery: IMAGES.bmwGallery.slice(1),
    vin: "WBS33AZ03PCL12345",
    vinDecoded: true,
    mileage: "8400",
    transmission: "Automatic",
    fuelType: "Gasoline",
    drivetrain: "RWD",
    engineSize: "3.0L Twin-Turbo I6",
    horsepower: "503 hp",
    exteriorColor: "Isle of Man Green",
    interiorColor: "Black Merino",
    seats: "4",
    doors: "2",
    mpgCity: "16",
    mpgHwy: "23",
    status: "paid",
    featured: true,
    views: 186,
    favorites: 14,
    chats: 5,
    features: [
      "Leather Seats",
      "Navigation",
      "Heated Seats",
      "Premium Audio",
      "Carbon Fiber Package",
      "Adaptive Cruise",
      "Backup Camera",
      "Apple CarPlay",
    ],
    highlights: ["One owner", "Dealer serviced", "No accidents", "M Driver’s Package"],
    city: "San Diego",
    state: "California",
    zip: "92101",
    titleStatus: "Clean",
    owners: "1",
    accidents: "0",
    historyReport: "Carfax — 0 accidents, 3 service records",
    listedLabel: "Listed 2 days ago",
    description:
      "Single-owner 2023 M4 Competition in Isle of Man Green. Always garaged in San Diego, BMW scheduled maintenance at Hoehn BMW. Carbon-bucket delete with regular sports seats, M Driver’s Package, and the 503-hp S58. Tires have 70% tread. Clean Carfax, no stories — priced to sell to a private buyer.",
  }),
  listing({
    id: "l2",
    ownerId: "u1",
    year: "2020",
    make: "Toyota",
    model: "Camry Hybrid",
    trim: "XLE",
    price: "24998",
    thumbnail: IMAGES.camryGallery[0],
    gallery: IMAGES.camryGallery.slice(1),
    vin: "4T1C31AK5LU123890",
    vinDecoded: false,
    mileage: "12500",
    fuelType: "Hybrid",
    engineSize: "2.5L I4 Hybrid",
    horsepower: "208 hp",
    exteriorColor: "Celestial Silver",
    interiorColor: "Ash",
    mpgCity: "51",
    mpgHwy: "53",
    status: "unpaid",
    views: 42,
    favorites: 3,
    chats: 1,
    state: "New York",
    city: "New York",
    zip: "10011",
    features: ["Backup Camera", "Apple CarPlay", "Heated Seats", "Blind Spot Monitor", "Sunroof"],
    highlights: ["Low miles", "Hybrid", "NYC garage kept"],
    listedLabel: "Draft · unpaid",
    description:
      "2020 Camry Hybrid XLE with 12,500 miles. One NYC owner, garage-kept in Chelsea. Battery health checked last month. Needs republish after an edit — listing is saved as Unpaid.",
  }),
  listing({
    id: "l3",
    ownerId: "u1",
    year: "2018",
    make: "Honda",
    model: "Civic",
    trim: "EX",
    price: "16400",
    thumbnail: IMAGES.honda,
    gallery: [IMAGES.honda, IMAGES.camry, IMAGES.white],
    mileage: "61000",
    engineSize: "1.5L Turbo",
    horsepower: "174 hp",
    mpgCity: "32",
    mpgHwy: "42",
    status: "sold",
    views: 90,
    favorites: 6,
    chats: 2,
    city: "Los Angeles",
    zip: "90034",
    listedLabel: "Sold last week",
    description: "Sold to a local buyer. Kept here as a record of a completed private-party sale.",
  }),
  listing({
    id: "l4",
    ownerId: "u-maya",
    year: "2024",
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range",
    price: "38990",
    thumbnail: IMAGES.teslaGallery[0],
    gallery: IMAGES.teslaGallery.slice(1),
    vin: "5YJ3E1EA5RF123456",
    vinDecoded: true,
    fuelType: "Electric",
    drivetrain: "AWD",
    engineSize: "Dual Motor",
    horsepower: "346 hp",
    exteriorColor: "Pearl White",
    interiorColor: "Black",
    mpgCity: "134 MPGe",
    mpgHwy: "126 MPGe",
    mileage: "6200",
    status: "paid",
    featured: true,
    views: 310,
    favorites: 28,
    chats: 9,
    state: "Texas",
    city: "Austin",
    zip: "78701",
    features: ["Autopilot", "Premium Audio", "Heated Seats", "Glass Roof", "Navigation", "Wireless Charging"],
    highlights: ["FSD-ready hardware", "White interior delete", "20\" Induction"],
    listedLabel: "Listed 5 days ago",
    description:
      "2024 Model 3 Long Range AWD. Austin one-owner, Supercharged mostly on home 48A. 19\" factory aero plus 20\" Induction set included. Clean title, no body work. Range test last week: 312 miles at 70% highway.",
  }),
  listing({
    id: "l5",
    ownerId: "u-derek",
    year: "2021",
    make: "Ford",
    model: "F-150",
    trim: "Lariat",
    bodyType: "Truck",
    price: "41500",
    thumbnail: IMAGES.truckGallery[0],
    gallery: IMAGES.truckGallery.slice(1),
    vin: "1FTFW1E85MFA23456",
    vinDecoded: true,
    mileage: "28000",
    drivetrain: "4WD",
    engineSize: "3.5L EcoBoost V6",
    horsepower: "400 hp",
    exteriorColor: "Antimatter Blue",
    interiorColor: "Black Leather",
    seats: "5",
    doors: "4",
    mpgCity: "18",
    mpgHwy: "24",
    status: "paid",
    views: 154,
    favorites: 11,
    chats: 4,
    state: "Colorado",
    city: "Denver",
    zip: "80205",
    features: ["Tow Package", "Leather Seats", "Backup Camera", "Apple CarPlay", "Heated Seats", "Navigation", "Blind Spot Monitor"],
    highlights: ["Max Recline", "Pro Power Onboard", "Spray-in bedliner"],
    listedLabel: "Listed 1 week ago",
    description:
      "2021 F-150 Lariat SuperCrew 4x4. Colorado truck — undercoated, bedlined, 7,200-lb tow package. No hail. Service at Mountain States Ford. Ready for a trailered boat or a ski weekend.",
  }),
  listing({
    id: "l6",
    ownerId: "u-sofia",
    year: "2019",
    make: "Porsche",
    model: "911",
    trim: "Carrera",
    bodyType: "Coupe",
    price: "98900",
    priceStance: "firm",
    thumbnail: IMAGES.porscheGallery[0],
    gallery: IMAGES.porscheGallery.slice(1),
    vin: "WP0AA2A99KS123450",
    vinDecoded: true,
    drivetrain: "RWD",
    engineSize: "3.0L Twin-Turbo Flat-6",
    horsepower: "379 hp",
    exteriorColor: "GT Silver",
    interiorColor: "Black Leather",
    seats: "4",
    doors: "2",
    mileage: "18600",
    mpgCity: "20",
    mpgHwy: "26",
    status: "paid",
    featured: true,
    views: 402,
    favorites: 33,
    chats: 7,
    state: "Florida",
    city: "Miami",
    zip: "33139",
    features: ["Leather Seats", "Premium Audio", "Navigation", "Sport Chrono", "PASM", "Backup Camera"],
    highlights: ["Sport Chrono", "PDK", "Two keys", "Window sticker"],
    listedLabel: "Listed yesterday",
    historyReport: "Porsche Official History — no paintwork",
    description:
      "2019 911 Carrera (992) in GT Silver. Miami car, ceramic-coated, stored indoors May–October. PDK, Sport Chrono, PASM. 18,600 miles. Books, two keys, and the original window sticker in the glovebox.",
  }),
  listing({
    id: "l7",
    ownerId: "u-marcus",
    year: "2022",
    make: "Jeep",
    model: "Wrangler",
    trim: "Rubicon",
    bodyType: "SUV",
    price: "44800",
    thumbnail: IMAGES.jeep,
    gallery: [IMAGES.jeep, ...IMAGES.truckGallery.slice(1, 4)],
    vin: "1C4HJXFG4NW123789",
    vinDecoded: true,
    drivetrain: "4WD",
    engineSize: "3.6L V6",
    horsepower: "285 hp",
    exteriorColor: "Sarge Green",
    interiorColor: "Black",
    seats: "5",
    doors: "4",
    mileage: "21400",
    mpgCity: "17",
    mpgHwy: "23",
    status: "paid",
    views: 98,
    favorites: 8,
    chats: 2,
    state: "Arizona",
    city: "Phoenix",
    zip: "85004",
    features: ["Tow Package", "Backup Camera", "Apple CarPlay", "Navigation", "Leather Seats"],
    highlights: ["Steel bumpers", "35s", "Lockers"],
    listedLabel: "Listed 4 days ago",
    description:
      "2022 Wrangler Unlimited Rubicon. Phoenix private seller. Factory lockers, 35s on beadlocks, steel bumpers. No rust. Soft top plus a hard top in the garage — buyer can take both.",
  }),
];

export const seedConversations: Conversation[] = [
  {
    id: "c1",
    listingId: "l1",
    listingTitle: "2023 BMW M4 Competition",
    listingThumb: IMAGES.bmwGallery[0],
    peerName: "Jordan Cole",
    lastMessage: "Is the price firm if I come this Saturday?",
    lastAt: "12m",
    unread: 2,
    messages: [
      {
        id: "c1m1",
        from: "them",
        kind: "text",
        text: "Still available? I can come Saturday.",
        at: "10:12 AM",
      },
      {
        id: "c1m2",
        from: "them",
        kind: "text",
        text: "Is the price firm if I come this Saturday?",
        at: "10:18 AM",
      },
    ],
  },
  {
    id: "c2",
    listingId: "l2",
    listingTitle: "2020 Toyota Camry Hybrid",
    listingThumb: IMAGES.camryGallery[0],
    peerName: "Priya Shah",
    lastMessage: "Can you send a video of the backup camera?",
    lastAt: "2h",
    unread: 0,
    messages: [
      {
        id: "c2m1",
        from: "them",
        kind: "text",
        text: "Can you send a video of the backup camera?",
        at: "Yesterday",
      },
    ],
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "n1",
    title: "New offer interest",
    body: "Jordan viewed your 2023 BMW M4 and sent a message.",
    time: "12m",
    read: false,
  },
  {
    id: "n2",
    title: "Listing quality tip",
    body: "Add a video to your Camry listing for +5 Quality bonus.",
    time: "1d",
    read: false,
  },
  {
    id: "n3",
    title: "Payment reminder",
    body: "Your Camry Hybrid is Unpaid — republish to go live.",
    time: "2d",
    read: true,
  },
];
